### ISSUE TITLE
Purpose of ServiceResult

### ISSUE THREAD

**Issue by MatthewScholefield** [visini/abstracting-fastapi-services#1]
When looking through the proposed design in the article, I was a little confused about the purpose of the `ServiceResult` class. My We already have `Response` and `HTTPException` from `FastAPI`/`Starlette` which seem to fulfill the same purpose. What benefit does having a dedicated `ServiceResult` provide? (for instance, what is a case where we would want to use `__enter__` and `__exit__` in a result rather than performing the behavior directly?)

**Comment by visini** [comment]
Hi @MatthewScholefield, thank you for your comments!

FastAPI is a flexible, unopinionated framework. This allows us to quickly outline an API with a handful of routes without any boilerplate. Contrary to [Django](https://docs.djangoproject.com/en/3.1/intro/tutorial01/#creating-a-project), for instance, all it takes is one module with a few lines of code, and we're good to go. 

This flexibility allows us to structure a FastAPI project, as it grows in complexity, exactly as we want. Building upon [this example](https://fastapi.tiangolo.com/tutorial/sql-databases/#review-all-the-files) in the docs, we can see that separating response and exception handling from CRUD operations makes sense as soon as the project grows above a handful of routes.

1. Handle requests and responses in `main` module:

```python
# main.py

@app.get("/users/{user_id}", response_model=schemas.User)
def read_user(user_id: int, db: Session = Depends(get_db)):
    db_user = crud.get_user(db, user_id=user_id)
    if db_user is None:
        raise HTTPException(status_code=404, detail="User not found")
    return db_user
```

2. Handle CRUD operations in `crud` module:

```python
# crud.py

def get_user(db: Session, user_id: int):
    return db.query(models.User).filter(models.User.id == user_id).first()
```

Now, let's assume you want to add logic to prevent returning data via this route for any `user` whose profile was deactivated. Should we put this logic in `main` or `crud`? This, I believe, relates to your question regarding why we would separate different parts of our implementation "rather than [perform] the behavior directly". The outcome in a functional sense is identical. However, in systematizing routes, models, schemas, business logic into distinct modules, I found it easier to reason about larger projects as a whole. 

The [companion article](https://camillovisini.com/article/abstracting-fastapi-services/) to this repository in fact inserted a layer in between the two layers described above: The _business logic_ layer, tasked with handling _anything_ that is not explicitly handling request-response and not explicitly handling lower-level tasks such as CRUD. This starts to make sense especially in a project of a certain size, which I will illustrate further.

The way I proposed thinking about separating both _concerns_ (e.g., request/response handling from CRUD operations, like in the example above) and _scope_ of the respective _services_ (by putting all related modules in their respective package, e.g., putting all routes into the package `route`) resulted in the following structure:

1. Separate everything related to the authentication service `auth` from the service handling static assets for all blogposts `blog`. Thus, business logic and CRUD operations for these two services are no longer maintained together in `crud.py`, but in `services/auth.py` and `services/blog.py`, respectively. 
2. Routes for `auth` and `blog` belong in `routes/auth.py` and `routes/blog.py` respectively
3. etc...

I conceptualized `ServiceResult` as the "interface" between the three layers of controller (routes), service (business logic) and data access (CRUD) for:
1. accepting requests (top down: controller → service → data access) and
2. returning responses (bottom up: data access → service → controller)

... thereby, the request-response flow "follows" / conceptually matches the call stack of the execution first "down" and then back "up" across the different components of the implementation.

Of course, we are completely free to directly call both `Response` and `HTTPException` in _any_ of the three layers instead of deliberately handling responses from the controller (routes) layer. Seeking to structure the project in a more rigid (and, of course, entirely arbitrary) fashion, I sought to reduce cognitive load and context switching when working on a specific part of the project. As such, in a larger project, it's always clear in which module to find all routes/CRUD operations/models/schemas/... belonging to a specific service. I hope this explained some of the reasoning behind this concept. I'm curious to hear your thoughts of alternative approaches!

**Comment by MatthewScholefield** [comment]
Thanks for the response!

> I conceptualized ServiceResult as the "interface" between the three layers of controller (routes), service (business logic) and data access (CRUD) for...

Just to clear up confusion, `ServiceResult` is the interface between only the service layer and the controller (on the returning side) right?


Assuming that's the case, I do see how it makes sense to provide a uniform result from the service layer (and also perhaps the idea that raising an `HTTPException` is a controller related task).

With regards to my comment on "performing the behavior directly", I was trying to understand if `ServiceResult`'s usage of `__enter__` and `__exit__` was to support custom context manager behavior in extended `ServiceResult` objects. Since I cannot imagine a case where you would want to return a context manager from a service, is this only used for syntactic convenience to allow extracting the value via a context manager? (Personally, I think letting consumers just use `.value`to access it would make more sense)

**Comment by visini** [comment]
> ServiceResult is the interface between only the service layer and the controller (on the returning side) right?

Exactly, I apologize for being imprecise.

> Since I cannot imagine a case where you would want to return a context manager from a service, is this only used for syntactic convenience to allow extracting the value via a context manager? (Personally, I think letting consumers just use .value to access it would make more sense)

Purely syntactic sugar. See the convenience function `handle_result`:

```python
def handle_result(result: ServiceResult):
    if not result.success:
        with result as exception:
            logger.error(f"{exception} | caller={caller_info()}")
            raise exception
    with result as result:
        return result
```

We could easily deal with `result.value` directly within routes, but (as seen in the example above) as soon as we need to add additional logic (such as logging) for _every_ route it would make sense to reduce this in order to reuse across routes. Also, it would be possible to not use any context manager and directly access `result.value` from a `handle_result` function, however it may look like.

**Comment by marcoaaguiar** [comment]
Sorry to bring this closed issue back to life, the whole ServiceResult seems a lot like the `concurrent.futures.Future`/`asyncio.Future`, which have a [result](https://docs.python.org/3/library/asyncio-future.html#asyncio.Future.result) method that does exactly what your `handle_result` does but using a method.

Why have a separate function (instead of a method) for handling the result? 
I mean you could have something like `ServiceResult.result_or_raise()` or `ServiceResult.result()` to keep it similar to Future interface.
